name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        run: |
          docker build -t tarixmanba-front-2 .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag tarixmanba-front-2 userhubdocker1/tarixmanba-front-2
          docker push userhubdocker1/tarixmanba-front-2

      - name: Disable strict host key checking
        run: | 
          mkdir -p ~/.ssh
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: SSH into server and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Prepare the SSH private key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add the server to known hosts to prevent SSH prompts
          ssh-keyscan -H 93.188.84.132 >> ~/.ssh/known_hosts

          # SSH into the server and deploy the Docker container
          ssh -T -i ~/.ssh/id_rsa root@93.188.84.132 << 'EOF'
            # Pull the latest Docker image
            docker pull userhubdocker1/tarixmanba-front-2

            # Stop and remove any existing container
            docker stop tarixmanba-front-container-2 || true
            docker rm tarixmanba-front-container-2 || true

            # Run a new container with the specified volume and port
            docker run --name tarixmanba-front-container-2 \
              -v /home/Tarix_manba/media:/app/media \
              -d -p 5400:5400 userhubdocker1/tarixmanba-front-2
          EOF
